import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useQuery, gql } from "@apollo/client";
import Link from "next/link";

// TODO: codegenの導入
const POSTS_QUERY = gql`
  query FetchPosts {
    listPost {
      title
      content
      user {
        name
        email
      }
    }
  }
`;

function Posts() {
  const { loading, error, data } = useQuery(POSTS_QUERY);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  return data.listPost.map(({ postId, title, content }) => (
    <div key={postId} className={styles.card}>
      <h2>{title}</h2>
      <p>{content}</p>
    </div>
  ));
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Boyaki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Boyaki</h1>

        <p>みんなのぼやきが集まる場所</p>
        <Link href="/mutter">
          <button>ぼやいてみる</button>
        </Link>

        <div className={styles.grid}>
          <Posts />
        </div>
      </main>

      <footer className={styles.footer}>Boyaki</footer>
    </div>
  );
};

export default Home;
