import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useMutation, gql } from "@apollo/client";
import Link from "next/link";
import { useRouter } from "next/router";

// TODO: codegenの導入
const POSTS_MUTATION = gql`
  mutation CreatePost($title: String!, $content: String!) {
    createPost(
      input: {
        title: $title
        content: $content
        userId: "aae0b6be-cd56-472f-b52e-17053082b2db"
      }
    ) {
      postId
    }
  }
`;

function Form() {
  const router = useRouter();
  let title: any;
  let content: any;
  const [addPost, { data, loading, error }] = useMutation(POSTS_MUTATION);

  if (loading) return <p>Submitting...</p>;
  if (error) return <p>Submission error! ${error.message}</p>;

  return (
    <div>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          addPost({
            variables: { title: title.value, content: content.value },
          });
          router.push("/");
        }}
      >
        <p>title</p>
        <input
          ref={(node) => {
            title = node;
          }}
          required
        />
        <br />
        <p>content</p>
        <input
          ref={(node) => {
            content = node;
          }}
          required
        />
        <br />
        <button type="submit">ぼやく</button>
      </form>
    </div>
  );
}

const Mutter: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Boyaki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Boyaki</h1>
        <p>みんなのぼやきが集まる場所</p>
        <Link href="/">
          <button>もどる</button>
        </Link>
        <Form />
      </main>

      <footer className={styles.footer}>Boyaki</footer>
    </div>
  );
};

export default Mutter;
