name: fe staging

on:
  push:
    branches: [ staging ]
    paths:
      - 'frontend/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup yarn
      run: npm install -g yarn

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    
    - name: Configure serverless.yml
      working-directory: frontend
      run: cp serverless-staging.yml serverless.yml

    - name: Download `.serverless` state from S3
      working-directory: frontend
      run: aws s3 sync s3://boyaki-serverless-state-bucket/staging/.serverless .serverless --delete

    - name: Build and Deploy
      working-directory: frontend
      run: |
        yarn
        yarn build
        yarn deploy
    
    - name: Upload `.serverless` state to S3
      working-directory: frontend
      run: aws s3 sync .serverless s3://boyaki-serverless-state-bucket/staging/.serverless --delete
